### ISSUE TITLE
Encontrar un proyecto viable

### ISSUE THREAD

**Issue by buritica** [colombia-dev/sancocho#1]

**Comment by juanD-M** [comment]
http://www.elespectador.com/noticias/educacion/gobierno-promueve-nueva-opcion-de-grado-universitarios-articulo-544510

**Comment by dav009** [comment]
Hallo Juan :+1: also ich war im Dezember in der naehe von Hamburg :( leider musste ich ploetzlich wiedermal zurueck nach London..

Es un buen articulo :) crees que podamos aportar algo?.

En una linea similar ayer estaba viendo:
http://www.meetup.com/Hacks-Hackers-Bogota/events/220435082/
piensan usar : www.poderopedia.org .

**Comment by dav009** [comment]
- Cartel del papel higienico ???
- Cartel de los cuadernos ???? 

plataforma para:
- Trackear precios
-  Deteccion de anomalias en precios ? podria usar [1]

---
[1] https://github.com/twitter/AnomalyDetection

**Comment by buritica** [comment]
Alguien se opone si paso este repo a http://github.com/colombia-dev ?

**Comment by dav009** [comment]
:+1:

**Comment by castilloedwin** [comment]
Me gustaría saber si hay algún proyecto Open Source en el cual colaborar.
Gracias

**Comment by edsadr** [comment]
@castilloedwin  https://github.com/colombia-dev/leonel
