### ISSUE TITLE
Informacion geografica - Estratos Socio Economicos ?

### ISSUE THREAD

**Issue by dav009** [colombia-dev/sancocho#10]
Existe algun dataset (OpenStreet map ? ) que contenga las delimitaciones de los estratos socieconomicos ?

**Comment by dav009** [comment]
Update:   Los datos los vende el [IDACA](www.ideca.gov.co).

**Comment by hugozap** [comment]
Buen dato, tienen algunos datasets en formato kmz, pero los términos de uso
no invitan mucho a crear cosas usándolos:
http://www.ideca.gov.co/sites/default/files/files/Condiciones-Cat%C3%A1logo%20de%20Datos%20Geogr%C3%A1ficos.pdf

**Comment by dav009** [comment]
@hugozap los KMZ no son "KMZ de verdad" son jpgs embebidos en un KMZ.
Osea, no tienes coordenadas. :[

**Comment by hugozap** [comment]
oh enserio? que mal, pero como hacen google maps / bing para pintar los
puntos? Necesitarían extraer las coordenadas del archivo

**Comment by dav009** [comment]
Gratis en el area de descargas esta el KMZ que mencionas que es simplemente un jpg embedido.

Si quieres el KMZ con coordenadas tienes que pagar.
https://medium.com/@dav009/opendata-colombia-pato-aventura-con-datos-geograficos-ideca-73ee03ddf3be

**Comment by hugozap** [comment]
Yo estoy viendo los kmz que aparecen en la sección Objetos geográficos
temáticos, uno de ellos por ej:
https://maps.google.com/maps?q=http://www.ideca.gov.co/kmz/IPS.kmz&output=classic&dg=feature

permite hacer click sobre cada punto y me muestra datos que incluyen las
coordenadas.

Veo que el link de descarga directa es distinto al que se le pasa a google
maps, :

1) (Link KMZ directo )
http://www.ideca.gov.co/sites/default/files/files/Datos/kmz/IPS.kmz
2) (Link Google maps) http://www.ideca.gov.co/kmz/IPS.kmz




2015-02-09 18:40 GMT-05:00 David Przybilla <notifications@github.com>:

**Comment by dav009** [comment]
:+1: gracias. 
retomare mi proyecto juguete en algun momento con el kmz mencionado :) yay!

**Comment by hugozap** [comment]
La pregunta es , que se podría hacer desde nuestro lado para que el IDECA
 y otros liberen sus datos? Creo que podemos inventarnos algún tipo de
estrategia, al menos para atraer atención y que se logre ejercer algún tipo
de presión. O al menos darle mas visibilidad al problema, que creo que es
el punto de entrada.

* Crear por ej listado de entidades públicas que no permiten al ciudadano
usar los datos
* Infografías donde quede claro el estado lamentable de la estrategia de
datos abiertos
* Fregar y fregar por las redes sociales
* ???

La presión y el 'shame cívico' pueden funcionar. Que opinan?

**Comment by dav009** [comment]
Buena idea.
Segun un post que lei a finales del anio pasado colombia aparecia en el top de openData, en mi opinion los criterios de evaluacion no eran ideales. 

Podriamos empezar haciendo la lista de entidades y datasets que a los cuales quisiéramos acceder.
Tambien haciendo una evaluacion a los datasets en datos.gov.co i.e: 

- Acceso(formatos, navegacion..)
- Categorias( hay muchisimos `lista de sitios turisticos de municipio x`)
- Granularidad( compendio estadisticos?)
- Anonimizacion de los datos
- Relevancia
- Uso? Alguein los esta usando/Usado
