### ISSUE TITLE
Comite de Camisetas

### ISSUE THREAD

**Issue by buritica** [colombia-dev/sancocho#13]

**Comment by alejandro-rios** [comment]
Como fueque!!

**Comment by ricardovalquin** [comment]
+1, qué hay que hacer? y en qué se puede ayudar?

**Comment by Krank2me** [comment]
+1, estamos para ayudar en pro de las camisetas XD

**Comment by alejandrovillegas** [comment]
+1, me apunto!!!!

**Comment by JenyMzo** [comment]
✋

**Comment by llanox** [comment]
👍

**Comment by llanox** [comment]
+1

**Comment by buritica** [comment]
listo formado el equipo

**Comment by buritica** [comment]
@jenymzo es la jefa. cuando podemos reunirnos 30 mins para organizarnos?

**Comment by JenyMzo** [comment]
el otro miércoles en la tarde pueden?

**Comment by Krank2me** [comment]
yo si

**Comment by JenyMzo** [comment]
Me confirman por favor quién puede estar por acá ----> https://doodle.com/poll/kc4um4k6yz9ss7ea

**Comment by Rogant** [comment]
Done, no se si los invitados puedan agregar mas opcciones?

**Comment by alejandro-rios** [comment]
Es a las 15:00, por que a esa hora me queda difícil, no se puede mas tarde??

**Comment by buritica** [comment]
si tienen sugerencias sobre diferentes tiempos pueden ponerlas aqui y @JenyMzo las agrega

**Comment by alejandro-rios** [comment]
Yo en semana puedo después de las 5PM, después de esa hora no hay problema.

**Comment by JenyMzo** [comment]
todos pueden el miércoles a las 5:30pm?

**Comment by Krank2me** [comment]
Yo puedo, no problem

**Comment by alejandro-rios** [comment]
yo tambien

**Comment by buritica** [comment]
nos vemos a las 5:30p BOG en https://splice.zoom.us/j/614574305
