### ISSUE TITLE
Comite de encuestas

### ISSUE THREAD

**Issue by buritica** [colombia-dev/sancocho#14]

**Comment by jdnichollsc** [comment]
me apunto, qué hay que hacer?

**Comment by Rogant** [comment]
how is the peanut?

**Comment by Angelfire** [comment]
Yo tambien puedo ayudar.

**Comment by ricardovalquin** [comment]
+1 que hay que hacer? como se puede ayudar?

**Comment by lauspadafora** [comment]
Cómo es la vuelta?

**Comment by manvedu** [comment]
Yo quiero ayudar💃

**Comment by unmultimedio** [comment]
Como referencia importante: https://insights.stackoverflow.com/survey/2018

**Comment by llanox** [comment]
+1

**Comment by jdnichollsc** [comment]
Comparto lo que se habló por Slack sobre trabajo remoto:
- Buritica:
```
si están trabajando para una empresa gringa que tenga financiamiento de VC en USA, son ustedes minimo mid-level engs y están ganando menos de 60k al año los están tumbando
`
``
- Yeiner
```
Remoto, para una empresa de USA? Menos de $2000 es regalar el trabajo. Aún así, una persona con bastante experiencia no debería menos de $4000-$4500/mes — De hecho, para una empresa de NY o SF, pagar un salario de USD $70k, $75k, $80k al año por un Senior dev…
```
```

Cuando una empresa Americana busca talento en Latino América, usualmente van a buscar barato por que los costos de vida son inferiores, etc. Uno quizás no pueda cobrar salario Americano, pero la idea es encontrar un sweet spot donde ambas partes queden felices, pero sin que el uno tumbe al otro.
El salario de un Sr. dev en NY no baja de $120k al año. Si la empresa tiene VC funding, y te está pagando $24k al año, está claramente aprovechándose de tí. Un sweet spot en ese caso estaría dentro del rango de los $60 a $80k anuales.
```
- Walter White
`para cubrir todo los parafiscales legales... sueldo * 1.56`
- Jaime Giraldo
```
Realmente es una cifra variable que puede ir desde un 40% hasta un 60%(o mas en salarios bajos) realmente las cifras son dependientes de los valores que reportes como salarios y tipos de aportes (origen de los salarios). En resumen este podría ser un esquema balanceado.
Salud 12.5%
Pension 12.5%
ARL Relativa (Tipo II) 1.044%
Cesantias 9.33%
Vacaciones 5.75%
Festivos Relativos hasta 18 días 4.93%
Fondo de Solidaridad 1%
TOTAL 55.4%
```
- Nicholls
```
yo tengo conocidos ganando 2500, 3500, 4200 y más
en la comunidad me habían dicho que uno debe de buscar 4000 USD en adelante siendo bueno y sabiendo inglés
por 2000 USD prefiero trabajar para una empresa local con más beneficios que remoto (obvio que depende de la experiencia) 
Además 110K ese es el promedio de un Senior en USA https://www.glassdoor.com/Salaries/senior-developer-salary-SRCH_KO0,16.htm
```

**Comment by buritica** [comment]
@jdnichollsc porfa no saquemos conversaciones del slack aqui al publico

**Comment by buritica** [comment]
@jdnichollsc ok, nos ayuda a crear un doodle para coordinar una reunion de 30 minutos y organizarnos?

**Comment by jdnichollsc** [comment]
ok, este es el link @buritica @Rogant @Angelfire @ricardovalquin @lauspadafora @manvedu @unmultimedio @llanox https://doodle.com/poll/k97xxpxar9nvf2dd

**Comment by dav009** [comment]
🙋‍♂️

**Comment by buritica** [comment]
Cierro, este issue y sigamos la conversacion en https://github.com/colombia-dev/data/issues/3

**Comment by buritica** [comment]
ping ^ (estamos teniendo ya la conversacion sobre la encuesta en ese issue, seria ideal publicar pronto)
