### ISSUE TITLE
Ideas Bogota Abierta

### ISSUE THREAD

**Issue by buritica** [colombia-dev/sancocho#15]
La alcaldia de bogota esta solicitando ideas, como comunidad podemos unirnos y apoyar una idea y participar en el proceso de seleccion ideacion, usemos este issue para nominar ideas y votar y luego publicamos la mas popular ahi.

https://bogotaabierta.co/reto/que-informacion-o-servicios-te-gustaria-encontrar-en-portal-bogota?id=que-informacion-o-servicios-te-gustaria-encontrar-en-portal-bogota

**Comment by jdnichollsc** [comment]
Web Site/Mobile App para visualizar la plata que reune el gobierno con nuestros impuestos y en que se va... en cada ciudad y municipio de Colombia, manteniendo una trazabilidad completa de lo que estamos invirtiendo los Colombianos

**Comment by buritica** [comment]
@jdnichollsc creo que esta propuesta es especifica a bogota, y la pagina que estan planeando. mas info esta en el link adjunto

**Comment by jdnichollsc** [comment]
Web Site/Mobile App para visualizar los principales problemas que tiene la ciudad y que los mismos ciudadanos reporten/voten por cuales propuestas el gobierno debería de invertir

**Comment by jdnichollsc** [comment]
@buritica podrían empezar por Bogotá con la primera propuesta, haciendo una tracking solo de esa ciudad e ir mejorando la plataforma para que pueda escalar a todo el país más adelante 👍
