### ISSUE TITLE
Nombres Subreddit

### ISSUE THREAD

**Issue by marianvilla** [colombia-dev/sancocho#16]
Hay interes de varios miembros del Slack de Colombia Dev en crear un subreddit con contenido similar a las discusiones que tenemos en #career pero para poder mantener un poco el historial de estas.

Este issue se usa como una encuesta para poder decidir el nombre del foro, especificamente lo que usariamos como subreddit, por ejemplo `r/elnombredelsubreddit`.

_Debido a que es un canal externo al Slack / comunidad de Coldev, estamos buscando un nombre que sea más genérico._

**Ejemplos tema**: Orientado a preguntas y respuestas frecuentes, ejemplo: qué silla es buena, q' escritorio me compro, etc. 

**Instrucciones** 

- sugerir: Sugieran abajo como comentarios el nombre, en formato de subreddit `r/sugerencia`
- para votar use el 👍 como reaccion en el comentario para indicar su prereferencia.

**Comment by buritica** [comment]
carrerasdevco

**Comment by buritica** [comment]
`r/trabajadorweb`

**Comment by buritica** [comment]
`r/trabajadoresweb`

**Comment by buritica** [comment]
`r/trabajadorwebco`

**Comment by buritica** [comment]
`r/pataconer@s`

**Comment by buritica** [comment]
`r/devcarcol`

**Comment by buritica** [comment]
`r/carrerasdevco`

**Comment by buritica** [comment]
`r/coldevcareer`

**Comment by CodeMaxter** [comment]
r/devco

**Comment by CodeMaxter** [comment]
r/devco

**Comment by jessecogollo** [comment]
r/comunidadColombianaDesarrolladores

**Comment by jessecogollo** [comment]
r/colombiaDevelopers

**Comment by alejandro-rios** [comment]
r/devsco

**Comment by jessecogollo** [comment]
colombia-dev
y me postulo como moderador.

**Comment by buritica** [comment]
`r/columbiadev`

**Comment by buritica** [comment]
@jessecogollo no es solo moderador sino le toca armar equipo

**Comment by jessecogollo** [comment]
Bueno, sí alguien quiere ser parte del equipo moderador... levante la mano :hand:

**Comment by CodeMaxter** [comment]
@jessecogollo, yo, aunque ¿debemos construir unas reglas primero no?

**Comment by CodeMaxter** [comment]
¿Además, las mismas reglas de Reddit no nos serían suficientes?

https://www.reddit.com/help/healthycommunities/
https://www.reddit.com/help/contentpolicy

Mi idea es que sea un lugar tranquilo sin tanta restricción, pero siempre con respeto.

**Comment by buritica** [comment]
Siendo ya 1 dia, cierro el issue ya que deben tener ideas de como seguir.
