### ISSUE TITLE
Mecanismo de Feedback

### ISSUE THREAD

**Issue by CodeMaxter** [colombia-dev/sancocho#20]
Es necesario que la comunidad cuente con un canal de feedback para la misma, y dado que aunque contó con los votos necesarios, fue rechazada la propuesta de un canal en Slack, se abre este issue para que discutamos y encontremos el mecanismo más adecuado

**Comment by jamlfy** [comment]
Seria interesante tener un lugar de discusion...

**Comment by CodeMaxter** [comment]
@katio propuso usar GitHub para hacer el feedback, la idea no me desagrada, pero hay que ver la viabilidad y forma de hacerlo como issues de GitHub, así que ya que no podemos usar el Slack oficial de Colombia Dev, hay que buscar la mejor alternativa.

**Comment by kuryaki** [comment]
Que les parece abrir issues en este repositorio? a manera de feedback?

**Comment by CodeMaxter** [comment]
@kuryaki Esa es la opción sobre la mesa, no sé si directamente sobre est repositiorio, quizás uno específico para tal fin, pero como tú dices, usando issues.

**Comment by kuryaki** [comment]
creo que este repo es el dispuesto para eso, si es un repo especifico a parte que uso tendria, en este repo se congregan muchas cosas propuestas, e iniciativas asi que issues de feedback tendrian aqui un lugar visible, lo que se podria hacer es manejar `labels` y asi diferenciar lo que es `feedback` de lo que es `propuesta` o `help wanted` etc..

**Comment by kuryaki** [comment]
https://github.com/colombia-dev/sancocho/issues/labels cree el label de feedback que podria usarse para tal fin

**Comment by CodeMaxter** [comment]
@kuryaki me gusta, no lo había pensado +1
